/* */
/* Created by joe on 6/23/25. */
/* */

#ifndef TEST_RESOLUTION_MACHINE_EXECUTE_POSITIVE_TESTS_H
#define TEST_RESOLUTION_MACHINE_EXECUTE_POSITIVE_TESTS_H
void test_execute_positive(void);

#endif /* TEST_RESOLUTION_MACHINE_EXECUTE_POSITIVE_TESTS_H */
