site_name: WebAssembly
nav:
    - Unit Description: "unit_description.md"
    - Use Cases:
          - "use-case.md"
    - Architectural Decisions:
          - Compiler:
                - "decisions/compiler/2026-02-03_00.md"