[[production]]
name = "entry"
type = "pure"
replacements = ["(%{paren set})"]
terminals = [""]

[[production]]
name = "paren set"
type = "pure"
replacements = ["(%{paren set})", "%{paren set}%{paren set}", ""]
terminals = [""]